require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Articles::ArticleDiagramBlocksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Articles::ArticleDiagramBlock. As you add validations to Articles::ArticleDiagramBlock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Articles::ArticleDiagramBlocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all articles_article_diagram_blocks as @articles_article_diagram_blocks" do
      article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:articles_article_diagram_blocks)).to eq([article_diagram_block])
    end
  end

  describe "GET #show" do
    it "assigns the requested articles_article_diagram_block as @articles_article_diagram_block" do
      article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
      get :show, params: {id: article_diagram_block.to_param}, session: valid_session
      expect(assigns(:articles_article_diagram_block)).to eq(article_diagram_block)
    end
  end

  describe "GET #new" do
    it "assigns a new articles_article_diagram_block as @articles_article_diagram_block" do
      get :new, params: {}, session: valid_session
      expect(assigns(:articles_article_diagram_block)).to be_a_new(Articles::ArticleDiagramBlock)
    end
  end

  describe "GET #edit" do
    it "assigns the requested articles_article_diagram_block as @articles_article_diagram_block" do
      article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
      get :edit, params: {id: article_diagram_block.to_param}, session: valid_session
      expect(assigns(:articles_article_diagram_block)).to eq(article_diagram_block)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Articles::ArticleDiagramBlock" do
        expect {
          post :create, params: {articles_article_diagram_block: valid_attributes}, session: valid_session
        }.to change(Articles::ArticleDiagramBlock, :count).by(1)
      end

      it "assigns a newly created articles_article_diagram_block as @articles_article_diagram_block" do
        post :create, params: {articles_article_diagram_block: valid_attributes}, session: valid_session
        expect(assigns(:articles_article_diagram_block)).to be_a(Articles::ArticleDiagramBlock)
        expect(assigns(:articles_article_diagram_block)).to be_persisted
      end

      it "redirects to the created articles_article_diagram_block" do
        post :create, params: {articles_article_diagram_block: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Articles::ArticleDiagramBlock.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved articles_article_diagram_block as @articles_article_diagram_block" do
        post :create, params: {articles_article_diagram_block: invalid_attributes}, session: valid_session
        expect(assigns(:articles_article_diagram_block)).to be_a_new(Articles::ArticleDiagramBlock)
      end

      it "re-renders the 'new' template" do
        post :create, params: {articles_article_diagram_block: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested articles_article_diagram_block" do
        article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
        put :update, params: {id: article_diagram_block.to_param, articles_article_diagram_block: new_attributes}, session: valid_session
        article_diagram_block.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested articles_article_diagram_block as @articles_article_diagram_block" do
        article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
        put :update, params: {id: article_diagram_block.to_param, articles_article_diagram_block: valid_attributes}, session: valid_session
        expect(assigns(:articles_article_diagram_block)).to eq(article_diagram_block)
      end

      it "redirects to the articles_article_diagram_block" do
        article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
        put :update, params: {id: article_diagram_block.to_param, articles_article_diagram_block: valid_attributes}, session: valid_session
        expect(response).to redirect_to(article_diagram_block)
      end
    end

    context "with invalid params" do
      it "assigns the articles_article_diagram_block as @articles_article_diagram_block" do
        article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
        put :update, params: {id: article_diagram_block.to_param, articles_article_diagram_block: invalid_attributes}, session: valid_session
        expect(assigns(:articles_article_diagram_block)).to eq(article_diagram_block)
      end

      it "re-renders the 'edit' template" do
        article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
        put :update, params: {id: article_diagram_block.to_param, articles_article_diagram_block: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested articles_article_diagram_block" do
      article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
      expect {
        delete :destroy, params: {id: article_diagram_block.to_param}, session: valid_session
      }.to change(Articles::ArticleDiagramBlock, :count).by(-1)
    end

    it "redirects to the articles_article_diagram_blocks list" do
      article_diagram_block = Articles::ArticleDiagramBlock.create! valid_attributes
      delete :destroy, params: {id: article_diagram_block.to_param}, session: valid_session
      expect(response).to redirect_to(articles_article_diagram_blocks_url)
    end
  end

end
