start();
//start
function start(){
$("#ball") 
 .velocity({ x: "-=363"})
$("#pole1")
 .velocity({ x: "-=145"})   
$("#pole2")
  .velocity({ x: "-=145"}) 
$("#pole3")
  .velocity({ x: "-=145"})  
$("#pole4")
 .velocity({ x: "-=145"})  
$("#pole5")
  .velocity({ x: "-=145"}) 
$("#pole6")
  .velocity({ x: "-=145"})  
$("#pole7")
  .velocity({ x: "-=145"})  
$("#pole8")
  .velocity({ x: "-=145"})  
$("#pole9")
  .velocity({ x: "-=145"})  
$("#pole10")
  .velocity({ x: "-=145"})  
$("#pole11")
  .velocity({ x: "-=145"}) 
$("#pole12")
 .velocity({ x: "-=145"})  
$("#pole13")
  .velocity({ x: "-=145"})  
$("#pole14")
  .velocity({ x: "-=145"})  
$("#pole15")
  .velocity({ x: "-=145"})  
$("#pole16")
 .velocity({ x: "-=145"})  
$("#pole17")
  .velocity({ x: "-=145"})  
$("#pole18")
  .velocity({ x: "-=145"})  
$("#pole19")
  .velocity({ x: "-=145"}) 
$("#pole20")
  .velocity({ x: "-=145"}) 
$("#pole21")
  .velocity({ x: "-=145"})  
$("#pole22")
  .velocity({ x: "-=145"}) 
$("#pole23")
  .velocity({ x: "-=145"}) 
$("#pole24")
 .velocity({ x: "-=145"},{complete:touch}) 

}

//balloon touch rubber
function touch(){
$("#Rpole2P")
  .velocity({ x: "+=25"}) 
$("#Rpole2M")
  .velocity({ x: "-=25"}) 
$("#Rpole4P")
  .velocity({ x: "+=25"}) 
$("#Rpole4M")
  .velocity({ x: "-=25"}) 
$("#Rpole6P")
  .velocity({ x: "+=25"}) 
$("#Rpole6M")
  .velocity({ x: "-=25"}) 
$("#Rpole8P")
  .velocity({ x: "+=25"}) 
$("#Rpole8M")
  .velocity({ x: "-=25"}) 
$("#Rpole10P")
  .velocity({ x: "+=25"}) 
$("#Rpole10M")
  .velocity({ x: "-=25"}) 
$("#Rpole12P")
  .velocity({ x: "+=25"}) 
$("#Rpole12M")
  .velocity({ x: "-=25"}) 
$("#pole24")
 .velocity({ x: "+=0"},{delay:3000,complete:left}) 
}
//left the rubber
function left(){
$("#ball") 
 .velocity({ x: "+=363"})
$("#pole1")
 .velocity({ x: "+=145"})   
$("#pole2")
.velocity({ x: "+=145"})  
$("#pole3")
 .velocity({ x: "+=145"})   
$("#pole4")
 .velocity({ x: "+=145"})  
$("#pole5")
.velocity({ x: "+=145"})  
$("#pole6")
  .velocity({ x: "+=145"})   
$("#pole7")
 .velocity({ x: "+=145"})    
$("#pole8")
  .velocity({ x: "+=145"})   
$("#pole9")
 .velocity({ x: "+=145"})    
$("#pole10")
  .velocity({ x: "+=145"})    
$("#pole11")
 .velocity({ x: "+=145"})  
$("#pole12")
 .velocity({ x: "+=145"})    
$("#pole13")
  .velocity({ x: "+=145"})   
$("#pole14")
  .velocity({ x: "+=145"})   
$("#pole15")
  .velocity({ x: "+=145"})  
$("#pole16")
.velocity({ x: "+=145"})  
$("#pole17")
 .velocity({ x: "+=145"})   
$("#pole18")
  .velocity({ x: "+=145"})  
$("#pole19")
 .velocity({ x: "+=145"})  
$("#pole20")
  .velocity({ x: "+=145"})  
$("#pole21")
 .velocity({ x: "+=145"})    
$("#pole22")
 .velocity({ x: "+=145"})  
$("#pole23")
 .velocity({ x: "+=145"}) 
$("#pole24")
 .velocity({ x: "+=145"},{delay:3000,complete:start})  
resert()
}

//resert all and begin
 function resert(){
  $("#Rpole2P")
  .velocity({ x: "-=25"}) 
$("#Rpole2M")
  .velocity({ x: "+=25"}) 
$("#Rpole4P")
  .velocity({ x: "-=25"}) 
$("#Rpole4M")
  .velocity({ x: "+=25"}) 
$("#Rpole6P")
  .velocity({ x: "-=25"}) 
$("#Rpole6M")
  .velocity({ x: "+=25"}) 
$("#Rpole8P")
  .velocity({ x: "-=25"}) 
$("#Rpole8M")
  .velocity({ x: "+=25"}) 
$("#Rpole10P")
  .velocity({ x: "-=25"}) 
$("#Rpole10M")
  .velocity({ x: "+=25"}) 
$("#Rpole12P")
  .velocity({ x: "-=25"}) 
$("#Rpole12M")
  .velocity({ x: "+=25"})       
 }   
 

    
 
